version: 4.0
#   _    _ _ _   _                 _                        _   _ _           _
#  | |  | | | | (_)               | |           /\         | | (_) |         | |
#  | |  | | | |_ _ _ __ ___   __ _| |_ ___     /  \   _ __ | |_ _| |__   ___ | |_
#  | |  | | | __| | '_ ` _ \ / _` | __/ _ \   / /\ \ | '_ \| __| | '_ \ / _ \| __|
#  | |__| | | |_| | | | | | | (_| | ||  __/  / ____ \| | | | |_| | |_) | (_) | |_
#  \____/|_|\__|_|_| |_| |_|\__,_|\__\___| /_/    \_\_| |_|\__|_|_.__/ \___/ \__|
#
#For any question / problem please open a ticket on my discord server,
#here is the link: https://discord.gg/vgsjmbXez3

# (!) DEBUG MODE (!)
#Setting it to true will allow me to help you better during the assistance however
#it results in a spam of useless messages in the console :(
debug: false

#UltimateAntibot V4 brings with it great
#improvements, ways of adapting the antibot
#to the performance of the machine based on
#its performance have been created.
detect-server-performance: true

# (!) WARNING (!)
# If set to true it will be able to calculate the time that the server takes to do all its operations!
# This involves creating a thread that could burden low-powered servers!
# It is recommended to use it only in dedicated servers or in vps with more than 8 cores!
# Use it at your own risk!
enable-latency-thread: false

# (!) NOTIFICATION (!)
#Enable bossbar notification on attack (1.9+)
enable-bossbar-automatic-notification: true

# (!) DISABLE CONSOLE ATTACK MESSAGE (!)
#
#If set to true, when you receive an attack on your server the
#console will not write any warning messages (referring only to UAB messages)
disable-console-attack-message: false

#Antibotmode has the utility of mitigating the attack, blacklisting + ip possible,
antibotmode:
  #Duration of the anti-botmode when activated
  keep: 15 #seconds
  #If there are 15 connections in 1 second the antibot mode will be activated!
  trigger: 15
  #Slowmode duration
  keep-slow: 60

#Pingmode allows player connections to your server!
pingmode:
  #Duration of the ping-mode when activated
  keep: 10
  #How many pings in 1 second does it take to activate the protection?
  trigger: 100
  #MotdKiller Protection
  #Send the server logo during a ping attack?
  send_info: false

#Works Only on Bungeecord Waterfall ect...
packetmode:
  #Duration of handshakemode
  keep: 15
  #How many blocked packets in 1 second for enable?
  trigger: 15
  #if the handshake has an invalid protocol do I have to blacklist it?
  blacklist-invalid-protocol: true

#Minimum online time to be whitelisted
playtime_for_whitelist: 10 #minutes

taskmanager:
  clearcache: 300 #seconds
  auth: 300 #seconds
  packet: 300 #seconds
  register: 300 #seconds
  update: 5 #seconds

checks:
  firstjoin:
    #enable firstjoin
    enabled: true
  #This check checks the number of accounts entered by the same ip within 60 seconds
  namechanger:
    #Clear cache time
    time: 60
    #max accounts to blackist
    limit: 3
    #enable?
    enabled: true
  #If an ip joins 35 times in 300 seconds
  superjoin:
    #Clear cache time
    time: 300
    #max joins in 60 seconds to get blacklisted
    limit: 35
    #enable?
    enabled: true
  auth:
    #Clear cache time
    time: 300
    #Allows users to whitelist
    #Through min-max ping
    ping: 3-5
    #Min max TimerCheck
    timer: 3-7
    #When the time for verification runs out,
    #you have 1.3 second to join
    between: 1300 #milliseconds
    #BlackList enable condition
    percent: 95
    #If player fail this check 15 times will be blacklisted
    maxfails: 15
    #If a player has to ping the verification,
    #the non-verifying players will have a counter of the times they pinged the
    #server to enter!
    #On bungeecord will use protocol name
    #On spigot will use the motd
    #Editable in messages.yml
    ping_interface: true
  slowjoin:
    #This check will check if a player sends a certain packet,
    #which the bots do not send, to 5 bots that do not send it
    #in 60 it will perform the various actionsù
    #WARNING
    #1) Only works on bungeecord || waterfall etc!
    #2) If you use plugins like Protocolize or Geyser it could give problems so you have to disable it
    #3) Some bots can bypass this check but it's at least something
    packet:
      time: 60 #seconds
      trigger: 5
      #dev only
      condition: 0
      blacklist: false
      kick: true
      antibotmode: true
      enabled: true
    #Check if bots have similar names
    #when 4 bots have similar names containing 5 similar
    #characters it will activate the antibot mode
    similar:
      time: 300 #seconds
      trigger: 4
      condition: 5
      blacklist: false
      kick: true
      antibotmode: true
      enabled: true
    #If 6 bots enter the server within 1 minute
    #having the same name length it will perform
    #the various actions
    lenght:
      time: 60 #seconds
      trigger: 6
      #Dev only
      condition: 15
      blacklist: false
      kick: true
      antibotmode: true
      enabled: true
    #if from same ip 4 accounts are online
    #will perform the various actions
    account:
      time: 0 #ignored here
      trigger: 4
      condition: 0 #ignored here
      blacklist: true
      kick: true
      antibotmode: true
      enabled: true

#This check allows you to verify your users during bot attacks!
#The site offers a free plan that you can access by signing up which gives you access to 1k requests per day.
#Each check will cost you 1 request and at the end of the daily requests you will have to wait for the next day!
proxycheck:
  #if key is not valid proxycheck is disabled (without errors in console (unless you have active debugging!))
  api-key: "enter-here-your-key"
  #Do I have to check every time a player enters? (There are no double checks unless you restart the server)
  check-slow-join: true
  #This check is only done later when most of the attack has been blacklisted (There are no double checks unless you restart the server)
  check-fast-join: true

#Custom Message filter only during bot / packet / ping attack
filter:
  - 'Another plugin has cancelled the connection for' #luckperms on spigot
  - 'The UUID the player is connecting with now is NOT Mojang-assigned' #luckperms on bungeecord

