version: 3.3
#   _    _ _ _   _                 _                        _   _ _           _
#  | |  | | | | (_)               | |           /\         | | (_) |         | |
#  | |  | | | |_ _ _ __ ___   __ _| |_ ___     /  \   _ __ | |_ _| |__   ___ | |_
#  | |  | | | __| | '_ ` _ \ / _` | __/ _ \   / /\ \ | '_ \| __| | '_ \ / _ \| __|
#  | |__| | | |_| | | | | | | (_| | ||  __/  / ____ \| | | | |_| | |_) | (_) | |_
#  \____/|_|\__|_|_| |_| |_|\__,_|\__\___| /_/    \_\_| |_|\__|_|_.__/ \___/ \__|
#
#For any question / problem please open a ticket on my discord server,
#here is the link: https://discord.gg/vgsjmbXez3

#debug mode
debug: false

#Antibotmode has the utility of mitigating the attack, blacklisting + ip possible,
antibotmode:
  #Duration of the anti-botmode when activated
  keep: 15 #seconds
  #If there are 15 connections in 1 second the antibot mode will be activated!
  trigger: 15

#Pingmode allows player connections to your server!
pingmode:
  #Duration of the ping-mode when activated
  keep: 10
  #How many pings in 1 second does it take to activate the protection?
  trigger: 100
  #MotdKiller Protection
  #Send the server logo during a ping attack?
  send_info: false

#Works Only on Bungeecord Waterfall ect...
packetmode:
  #Duration of handshakemode
  keep: 10
  #How many handshake in 1 second to enable?
  trigger: 150 #Set (Your online players * 4) | If you have 40 average online players you have to do 40 x 3 and the result will be the value to write
  #if the handshake has an invalid protocol do I have to blacklist it?
  blacklist-invalid-protocol: true

#Minimum online time to be whitelisted
playtime_for_whitelist: 2 #minutes

taskmanager:
  clearcache: 15 #minutes
  auth: 300 #seconds
  packet: 300 #seconds
  register: 300 #seconds

checks:
  firstjoin:
    #enable firstjoin
    enabled: true
  #This check checks the number of accounts entered by the same ip within 60 seconds
  namechanger:
    #Clear cache time
    time: 60
    #max accounts to blackist
    limit: 3
    #enable?
    enabled: true
  #If an ip joins 35 times in 300 seconds
  superjoin:
    #Clear cache time
    time: 300
    #max joins in 60 seconds to get blacklisted
    limit: 35
    #enable?
    enabled: true
  auth:
    #Clear cache time
    time: 300
    #Allows users to whitelist
    #Through min-max ping
    ping: 10-15
    #Min max TimerCheck
    timer: 5-10
    #When the time for verification runs out,
    #you have 1.2 second to join
    between: 1200 #milliseconds
    #BlackList enable condition
    percent: 95
    #If a player has to ping the verification,
    #the non-verifying players will have a counter of the times they pinged the
    #server to enter!
    #On bungeecord will use protocol name
    #On spigot will use the motd
    #Editable in messages.yml
    ping_interface: true
    #Enable this check
    enabled: true
  slowjoin:
    #This check will check if a player sends a certain packet,
    #which the bots do not send, to 5 bots that do not send it
    #in 60 it will perform the various actionsù
    #WARNING
    #1) Only works on bungeecord || waterfall etc!
    #2) If you use plugins like Protocolize or Geyser it could give problems so you have to disable it
    #3) Some bots can bypass this check but it's at least something
    packet:
      time: 60 #seconds
      trigger: 5
      blacklist: false
      kick: true
      antibotmode: true
      enabled: true


